import 'package:flutter/cupertino.dart';

import '../../../../../../constants/qate3_model.dart';

class Qate3Cars extends StatelessWidget {
  const Qate3Cars({super.key});

  @override
  Widget build(BuildContext context) {
    return Qate3Model(
      itemCountCallback: (index) {
        return 35;
      },
      barTitle: ' منتجات السيارات المقاطعة',
      imagePath1: 'assets/cars/Qate3/1.png',
      imagePath2: 'assets/cars/Qate3/2.png',
      imagePath3: 'assets/cars/Qate3/3.png',
      imagePath4: 'assets/cars/Qate3/4.png',
      imagePath5: 'assets/cars/Qate3/5.png',
      imagePath6: 'assets/cars/Qate3/6.png',
      imagePath7: 'assets/cars/Qate3/7.png',
      imagePath8: 'assets/cars/Qate3/8.png',
      imagePath9: 'assets/cars/Qate3/9.png',
      imagePath10: 'assets/cars/Qate3/10.png',
      imagePath11: 'assets/cars/Qate3/11.png',
      imagePath12: 'assets/cars/Qate3/12.png',
      imagePath13: 'assets/cars/Qate3/13.png',
      imagePath14: 'assets/cars/Qate3/14.png',
      imagePath15: 'assets/cars/Qate3/15.png',
      imagePath16: 'assets/cars/Qate3/16.png',
      imagePath17: 'assets/cars/Qate3/17.png',
      imagePath18: 'assets/cars/Qate3/18.png',
      imagePath19: 'assets/cars/Qate3/19.png',
      imagePath20: 'assets/cars/Qate3/20.png',
      imagePath21: 'assets/cars/Qate3/21.png',
      imagePath22: 'assets/cars/Qate3/22.png',
      imagePath23: 'assets/cars/Qate3/23.png',
      imagePath24: 'assets/cars/Qate3/24.png',
      imagePath25: 'assets/cars/Qate3/25.png',
      imagePath26: 'assets/cars/Qate3/26.png',
      imagePath27: 'assets/cars/Qate3/27.png',
      imagePath28: 'assets/cars/Qate3/28.png',
      imagePath29: 'assets/cars/Qate3/29.png',
      imagePath30: 'assets/cars/Qate3/30.png',
      imagePath31: 'assets/cars/Qate3/31.png',
      imagePath32: 'assets/cars/Qate3/32.png',
      imagePath33: 'assets/cars/Qate3/33.png',
      imagePath34: 'assets/cars/Qate3/34.png',
      imagePath35: 'assets/cars/Qate3/35.png',
      title1: 'بي إم دابليو',
      title2: 'مرسيدس ',
      title3: ' فيراري',
      title4: 'بورش',
      title5: ' دودج',
      title6: ' مازيراتي',
      title7: 'لامبورجيني ',
      title8: 'تسلا',
      title9: 'أودي',
      title10: 'جاجوار',
      title11: 'كيا',
      title12: 'ستروين ',
      title13: 'جيب كرايسلر ',
      title14: ' جي إم سي',
      title15: ' متسوبيشي ',
      title16: ' سوبارو ',
      title17: ' بريليانس ',
      title18: ' لكزس شيري',
      title19: ' تويوتا',
      title20: ' شيفروليه',
      title21: 'فيات ',
      title22: ' فورد',
      title23: 'هوندا ',
      title24: 'ايسوزو  ',
      title25: 'مازدا ',
      title26: ' نيسان',
      title27: 'أوبل ',
      title28: ' بيجو رينو',
      title29: 'فولكس واجن ',
      title30: ' فولفو',
      title31: ' دايو ',
      title32: ' كاديلاك ',
      title33: ' سوزوكي',
      title34: 'سكودا ',
      title35: ' هيونداي',
    );
  }
}
